/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homeScreen` | `/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/lopHocPhan/[id]/_context`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/dashboard` | `/lopHocPhan/[id]/dashboard`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/notifications` | `/lopHocPhan/[id]/notifications`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/peopleScreen` | `/lopHocPhan/[id]/peopleScreen`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/homeScreen` | `/homeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/lopHocPhan/[id]/_context`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/dashboard` | `/lopHocPhan/[id]/dashboard`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/notifications` | `/lopHocPhan/[id]/notifications`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/peopleScreen` | `/lopHocPhan/[id]/peopleScreen`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/homeScreen${`?${string}` | `#${string}` | ''}` | `/homeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homeScreen` | `/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | `/lopHocPhan/${Router.SingleRoutePart<T>}/_context` | `/lopHocPhan/${Router.SingleRoutePart<T>}${'/(tabs)'}/dashboard` | `/lopHocPhan/${Router.SingleRoutePart<T>}/dashboard` | `/lopHocPhan/${Router.SingleRoutePart<T>}${'/(tabs)'}/notifications` | `/lopHocPhan/${Router.SingleRoutePart<T>}/notifications` | `/lopHocPhan/${Router.SingleRoutePart<T>}${'/(tabs)'}/peopleScreen` | `/lopHocPhan/${Router.SingleRoutePart<T>}/peopleScreen` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/lopHocPhan/[id]/_context`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/dashboard` | `/lopHocPhan/[id]/dashboard`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/notifications` | `/lopHocPhan/[id]/notifications`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lopHocPhan/[id]${'/(tabs)'}/peopleScreen` | `/lopHocPhan/[id]/peopleScreen`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
